### ISSUE TITLE
Use environment variables for secrets

### ISSUE THREAD

**Issue by MrSlimCoder** [alee-kolachi/top_notch_writer_web_app#1]
Hi ali ! i saw you recent commit but in this commit i found a security issue in [login file](https://github.com/alee-kolachi/top_notch_writer_web_app/blob/master/login.js) please don't write secret hard coded instead use [.env](https://www.npmjs.com/package/dotenv)

**Comment by alee-kolachi** [comment]
Oh, I see! Thanks for informing sir. I accidentally committed the code without thinking about that secret information. I am thinking to fix it soon.

**Comment by MrSlimCoder** [comment]
Closed #1
